spring:

  datasource:
    content:
      # localhost port content
      url: jdbc:postgresql://localhost:5433/content
      username: marat
      password: '0000'
      driver-class-name: org.postgresql.Driver
      hikari:
        connectionTimeout: 44444

    users:
      url: jdbc:postgresql://localhost:5432/users
      username: nexoc
      password: '0880'
      driver-class-name: org.postgresql.Driver

  #jpa:
    #hibernate:
      #ddl-auto: create-drop
    #show-sql: true
    #properties:
      #hibernate:
        #format_sql: true

  jpa:
    content:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
    users:
      hibernate:
        ddl-auto: create-drop

      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  project:
    poster: poster/

base:
  url: "http://localhost:8080"